# ===========================
# Datasource
# ===========================
quarkus.datasource.db-kind=postgresql 
quarkus.datasource.username=<user348a>
quarkus.datasource.password=<543182*L9d>

quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/db_test_shop
quarkus.datasource.jdbc.max-size=16

# ===========================
# Hibernate ORM
# ===========================
quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.dialect=org.hibernate.dialect.PostgreSQLDialect
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.database.default-schema=public
# ===========================
# HTTP
# ===========================
quarkus.http.port=8080

# ===========================
# JWT
# ===========================
mp.jwt.verify.publickey.location=META-INF/resources/publicKey.pem
smallrye.jwt.sign.key.location=META-INF/resources/privateKey.pem

mp.jwt.verify.issuer=https://testshop.com

quarkus.http.auth.form.cookie-name=auth_token

# ===========================
# OpenAPI / Swagger
# ===========================
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger