# ===========================
# Datasource
# ===========================
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=ecommerce
quarkus.datasource.password=ecommerce123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/ecommerce_dev

# ===========================
# Hibernate ORM
# ===========================
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# ===========================
# HTTP
# ===========================
quarkus.http.port=8080

# ===========================
# JWT
# ===========================
mp.jwt.verify.issuer=https://ecommerce.com
quarkus.smallrye-jwt.enabled=true

# ===========================
# OpenAPI / Swagger
# ===========================
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger